### ISSUE TITLE
Erinmabsizde 89mb li kod yozishga 😅

### ISSUE THREAD

**Issue by komildeveloper** [AbstractBits/the-longest-function-in-the-world#1]

**Comment by muocod** [comment]
Qo'lda yozilmagan bu )))

**Comment by komildeveloper** [comment]
> Qo'lda yozilmagan bu )))

Copy Paste mi?

**Comment by muocod** [comment]
2 million qator narsa copy paste bo'ladimi?!

**Comment by komildeveloper** [comment]
> 2 million qator narsa copy paste bo'ladimi?!

😅nma unda oka jovobi

**Comment by muocod** [comment]
fs module bilan qilingan adashmasam

**Comment by komildeveloper** [comment]
> fs module bilan qilingan adashmasam

rahmat oka jovob uchun
